### ISSUE TITLE
Installed but pause,play option not available

### ISSUE THREAD

**Issue by Dumidu2023** [flathub/org.videolan.VLC.Plugin.pause_click#2]
I installed this VLC plugin as described in the instructions on my zorin OS 16. However I cannot find the pause play option on VLC control interfaces. Could somebody please help me to solve this issue ?

**Comment by nurupo** [comment]
What is the output of:

```sh
flatpak info org.videolan.VLC
flatpak info org.videolan.VLC.Plugin.pause_click
```

commands?

Also, does the option appear if you start VLC via `flatpak run org.videolan.VLC`?

**Comment by nurupo** [comment]
And just to make sure you are looking at the right place, the two options should appear in here (both need to be checked for the plugin to activate!):

![vlc_help1](https://user-images.githubusercontent.com/1855294/230748030-b562bef5-5d06-4466-a501-6b035511aee9.png)

![vlc_help2](https://user-images.githubusercontent.com/1855294/230748032-dfbe45e6-7072-4cf6-b65e-fd6582abbe71.png)

**Comment by Dumidu2023** [comment]
I think the problem was this plugin's incampatibility with different versions of VLC. I had installed the VLC player using software catelog graphical interface of the operating system. I uninstalled it and re installed the VLC using command shell.  By doing that I could install 3.0.9.2 vetenari. Now I see the options, and the plugin is working perfectly. Thank you very much for the great plugin.

**Comment by nurupo** [comment]
Cool, glad you have sorted it out.

By the way, I want to point out that the latest version of VLC on Flathub is 3.0.18, not 3.0.9.2. So unless you have a compelling reason to use that particular older version, you might be missing out on 3 years of [security and bug fixes](https://code.videolan.org/videolan/vlc/-/blob/3.0.18/NEWS).
