### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.videolan.VLC.Plugin.pause_click#5]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by nurupo** [comment]
Thanks for the heads-up, @bbhtt!

>[Flatpak-builder (>= 1.3.4), can compose metadata for extensions automatically and it is no longer required to manually compose them through commands in the manifest.](https://docs.flatpak.org/en/latest/extension.html#extension-manifest)

While I would like to remove the compose entirely, my distro does not package `flatpak-builder` >= 1.3.4 yet, so I will have to switch to `appstreamcli` for the time being instead, as I want to still be able to build the flatpak locally for testing purposes.
